-- Generated by vehicle-lookup/refresh_vehicle_model_year.py.
-- Customer-facing 2027 model-year refresh from NHTSA vPIC with reviewed Prokvik classifications.
-- Exact make matching prevents partial manufacturer contamination.

begin;

with reviewed_rows (
  year, make, model, vehicle_class, pricing_group,
  classification_source, review_status, is_commercial
) as (
values
  (2027, 'Acura', 'ADX', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Acura', 'Integra', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Acura', 'MDX', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Acura', 'RDX', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Acura', 'ZDX', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Alfa Romeo', 'Giulia (952)', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Alfa Romeo', 'Stelvio', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Alfa Romeo', 'Tonale', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'A3', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'A5', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'A6', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'A8 L', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'Q3', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'Q4', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'Q5', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'Q6', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'Q7', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'Q8', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'Q9', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'RS 3', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'RS 7', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'RS e-tron GT', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'RS Q8', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'S e-tron GT', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'S3', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'S5', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'S6', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'S8', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'SQ5', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'SQ6', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'SQ7', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'SQ8', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Audi', 'SQ9', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Bentley', 'Bentayga', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Bentley', 'Continental', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Bentley', 'Flying Spur', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', '228', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', '430i', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', '530i', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', '540i', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', '550e', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', '740i', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'i5', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'i7', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'iX', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'M2', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'M235', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'M240i', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'M3', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'M4', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'M440i', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'M5', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'X1', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'X2', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'X3', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'X6', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'X7', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'BMW', 'XM', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Buick', 'Enclave', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Buick', 'Encore GX', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Buick', 'Envision', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Buick', 'Envista', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Cadillac', 'Celestiq', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Cadillac', 'CT4', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Cadillac', 'CT5', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Cadillac', 'Escalade', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Cadillac', 'Escalade ESV', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Cadillac', 'Escalade IQ', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Cadillac', 'Escalade IQL', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Cadillac', 'Lyriq', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Cadillac', 'Optiq', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Cadillac', 'Vistiq', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Cadillac', 'XT5', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Blazer', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Bolt', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Colorado', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Corvette', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Equinox', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Express', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Silverado', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Silverado HD', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Suburban', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Suburban HD', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Tahoe', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Trailblazer', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Traverse', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chevrolet', 'Trax', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chrysler', 'Grand Caravan', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Chrysler', 'Pacifica', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Dodge', 'Charger', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Dodge', 'Durango', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Fiat', '500e', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', '''34', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'Bronco', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'Bronco Sport', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'Escape', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'Expedition', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'Expedition MAX', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'Explorer', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'F-150', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'F-250', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'F-350', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'Maverick', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'Mustang', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'Mustang GTD', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'Mustang Mach-E', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'Ranger', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ford', 'Transit', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Genesis', 'G70', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Genesis', 'G80', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Genesis', 'G90', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Genesis', 'GV60', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Genesis', 'GV60 Magma', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Genesis', 'GV70', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Genesis', 'GV80', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'GMC', 'Acadia', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'GMC', 'Canyon', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'GMC', 'Hummer EV Pickup', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'GMC', 'Hummer EV SUV', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'GMC', 'Savana', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'GMC', 'Sierra', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'GMC', 'Sierra HD', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'GMC', 'Terrain', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'GMC', 'Yukon', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'GMC', 'Yukon XL', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Honda', 'Accord', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Honda', 'Civic', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Honda', 'Civic Si', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Honda', 'Civic Type R', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Honda', 'CR-V', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Honda', 'HR-V', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Honda', 'Odyssey', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Honda', 'Passport', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Honda', 'Pilot', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Honda', 'Prelude', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Honda', 'Prologue', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Honda', 'Ridgeline', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Elantra', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Elantra N', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Ioniq 5', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Ioniq 5 N', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Ioniq 6 N', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Ioniq 9', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Kona', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Nexo', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Palisade', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Santa Cruz', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Sonata', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Tucson', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Hyundai', 'Venue', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Infiniti', 'QX60', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Infiniti', 'QX65', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Infiniti', 'QX80', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Jaguar', 'F-PACE', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Jeep', 'Cherokee', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Jeep', 'Compass', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Jeep', 'Gladiator', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Jeep', 'Grand Cherokee', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Jeep', 'Grand Cherokee L', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Jeep', 'Grand Wagoneer', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Jeep', 'Grand Wagoneer L', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Jeep', 'Recon', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Jeep', 'Wagoneer S', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Jeep', 'Wrangler', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Kia', 'Carnival', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Kia', 'EV3', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Kia', 'EV6', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Kia', 'EV9', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Kia', 'K4', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Kia', 'K5', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Kia', 'Niro', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Kia', 'Seltos', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Kia', 'Sorento', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Kia', 'Sportage', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Kia', 'Telluride', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Land Rover', 'Discovery', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Land Rover', 'Discovery Sport', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Land Rover', 'Range Rover', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Land Rover', 'Range Rover Evoque', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Land Rover', 'Range Rover Sport', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Land Rover', 'Range Rover Velar', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lexus', 'ES', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lexus', 'IS', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lexus', 'LC', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lexus', 'LS', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lexus', 'LX', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lexus', 'NX', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lexus', 'RX', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lexus', 'RZ', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lexus', 'TX', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lexus', 'UX', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lincoln', 'Aviator', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lincoln', 'Corsair', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lincoln', 'Nautilus', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lincoln', 'Navigator', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lincoln', 'Navigator L', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lucid', 'Air', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Lucid', 'Gravity', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mazda', 'CX-30', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mazda', 'CX-5', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mazda', 'CX-50', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mazda', 'CX-70', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mazda', 'CX-90', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mazda', 'Mazda3', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mazda', 'MX-5', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mercedes-Benz', 'CLA-Class', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mercedes-Benz', 'CLE', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mercedes-Benz', 'E-Class', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mercedes-Benz', 'EQE-Class SUV', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mercedes-Benz', 'EQS-Class SUV', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mercedes-Benz', 'eSprinter', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mercedes-Benz', 'G-Class', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mercedes-Benz', 'GLC-Class', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mercedes-Benz', 'S-Class', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mercedes-Benz', 'SL-Class', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mercedes-Benz', 'Sprinter', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mini', 'Cooper Convertible', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mini', 'Countryman', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mini', 'Hardtop', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mitsubishi', 'Outlander', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Mitsubishi', 'Outlander Sport', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Nissan', 'Altima', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Nissan', 'Ariya MPV', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Nissan', 'Armada', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Nissan', 'Frontier', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Nissan', 'Kicks MPV', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Nissan', 'Leaf', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Nissan', 'Murano', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Nissan', 'Nissan Z', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Nissan', 'Pathfinder', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Nissan', 'Rogue', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Nissan', 'Sentra', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Polestar', 'Polestar 2', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Polestar', 'Polestar 3', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Polestar', 'Polestar 4', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Porsche', '911', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Porsche', 'Cayenne', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Porsche', 'Macan', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Porsche', 'Panamera', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Porsche', 'Taycan', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ram', '1500', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ram', '2500', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ram', '3500', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ram', 'ProMaster 1500', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ram', 'ProMaster 2500', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Ram', 'ProMaster 3500', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Rivian', 'R1S', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Rivian', 'R1T', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Rivian', 'R2', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Subaru', 'Ascent', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Subaru', 'BRZ', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Subaru', 'Crosstrek', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Subaru', 'Forester', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Subaru', 'Impreza', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Subaru', 'Outback', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Subaru', 'Solterra', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Subaru', 'Trailseeker', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Subaru', 'Uncharted', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Subaru', 'WRX', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Tesla', 'Cybercab', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Tesla', 'Cybertruck', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Tesla', 'Model 3', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Tesla', 'Model Y', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', '4Runner', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'bZ', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'bZ Woodland', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'C-HR', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Camry', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Corolla', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Corolla Cross', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Crown', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Crown Signia', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'GR Corolla', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'GR86', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Grand Highlander', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Highlander', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Land Cruiser', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Mirai', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Prius', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Prius Prime (PHEV)', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'RAV4', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'RAV4 Prime (PHEV)', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Sequoia', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Sienna', 'van', 'Van', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Supra', 'coupe', 'Coupe', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Tacoma', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Toyota', 'Tundra', 'truck', 'Truck', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volkswagen', 'Atlas', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volkswagen', 'Golf GTI', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volkswagen', 'Golf R', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volkswagen', 'ID.4', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volkswagen', 'Jetta', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volkswagen', 'Jetta GLI', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volkswagen', 'Taos', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volkswagen', 'Tiguan', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volvo', 'EC40', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volvo', 'EX30', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volvo', 'EX30 CC', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volvo', 'EX40', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volvo', 'EX60', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volvo', 'EX90', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volvo', 'S90', 'sedan', 'Sedan', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volvo', 'V60CC', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volvo', 'V90CC', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volvo', 'XC40', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volvo', 'XC60', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false),
  (2027, 'Volvo', 'XC90', 'suv', 'SUV', 'nhtsa_vpic_2027_reviewed', 'ok', false)
)
insert into public.vehicle_lookup (
  year, make, model, vehicle_class, pricing_group,
  classification_source, review_status, is_commercial
)
select * from reviewed_rows
on conflict (year, make, model) do update set
  vehicle_class = excluded.vehicle_class,
  pricing_group = excluded.pricing_group,
  classification_source = excluded.classification_source,
  review_status = excluded.review_status,
  is_commercial = excluded.is_commercial;

-- Remove model-year rows that are no longer in the reviewed current vPIC snapshot.
delete from public.vehicle_lookup
where year = 2027
  and (lower(trim(make)), lower(trim(model))) not in (
values
  ('acura', 'adx'),
  ('acura', 'integra'),
  ('acura', 'mdx'),
  ('acura', 'rdx'),
  ('acura', 'zdx'),
  ('alfa romeo', 'giulia (952)'),
  ('alfa romeo', 'stelvio'),
  ('alfa romeo', 'tonale'),
  ('audi', 'a3'),
  ('audi', 'a5'),
  ('audi', 'a6'),
  ('audi', 'a8 l'),
  ('audi', 'q3'),
  ('audi', 'q4'),
  ('audi', 'q5'),
  ('audi', 'q6'),
  ('audi', 'q7'),
  ('audi', 'q8'),
  ('audi', 'q9'),
  ('audi', 'rs 3'),
  ('audi', 'rs 7'),
  ('audi', 'rs e-tron gt'),
  ('audi', 'rs q8'),
  ('audi', 's e-tron gt'),
  ('audi', 's3'),
  ('audi', 's5'),
  ('audi', 's6'),
  ('audi', 's8'),
  ('audi', 'sq5'),
  ('audi', 'sq6'),
  ('audi', 'sq7'),
  ('audi', 'sq8'),
  ('audi', 'sq9'),
  ('bentley', 'bentayga'),
  ('bentley', 'continental'),
  ('bentley', 'flying spur'),
  ('bmw', '228'),
  ('bmw', '430i'),
  ('bmw', '530i'),
  ('bmw', '540i'),
  ('bmw', '550e'),
  ('bmw', '740i'),
  ('bmw', 'i5'),
  ('bmw', 'i7'),
  ('bmw', 'ix'),
  ('bmw', 'm2'),
  ('bmw', 'm235'),
  ('bmw', 'm240i'),
  ('bmw', 'm3'),
  ('bmw', 'm4'),
  ('bmw', 'm440i'),
  ('bmw', 'm5'),
  ('bmw', 'x1'),
  ('bmw', 'x2'),
  ('bmw', 'x3'),
  ('bmw', 'x6'),
  ('bmw', 'x7'),
  ('bmw', 'xm'),
  ('buick', 'enclave'),
  ('buick', 'encore gx'),
  ('buick', 'envision'),
  ('buick', 'envista'),
  ('cadillac', 'celestiq'),
  ('cadillac', 'ct4'),
  ('cadillac', 'ct5'),
  ('cadillac', 'escalade'),
  ('cadillac', 'escalade esv'),
  ('cadillac', 'escalade iq'),
  ('cadillac', 'escalade iql'),
  ('cadillac', 'lyriq'),
  ('cadillac', 'optiq'),
  ('cadillac', 'vistiq'),
  ('cadillac', 'xt5'),
  ('chevrolet', 'blazer'),
  ('chevrolet', 'bolt'),
  ('chevrolet', 'colorado'),
  ('chevrolet', 'corvette'),
  ('chevrolet', 'equinox'),
  ('chevrolet', 'express'),
  ('chevrolet', 'silverado'),
  ('chevrolet', 'silverado hd'),
  ('chevrolet', 'suburban'),
  ('chevrolet', 'suburban hd'),
  ('chevrolet', 'tahoe'),
  ('chevrolet', 'trailblazer'),
  ('chevrolet', 'traverse'),
  ('chevrolet', 'trax'),
  ('chrysler', 'grand caravan'),
  ('chrysler', 'pacifica'),
  ('dodge', 'charger'),
  ('dodge', 'durango'),
  ('fiat', '500e'),
  ('ford', '''34'),
  ('ford', 'bronco'),
  ('ford', 'bronco sport'),
  ('ford', 'escape'),
  ('ford', 'expedition'),
  ('ford', 'expedition max'),
  ('ford', 'explorer'),
  ('ford', 'f-150'),
  ('ford', 'f-250'),
  ('ford', 'f-350'),
  ('ford', 'maverick'),
  ('ford', 'mustang'),
  ('ford', 'mustang gtd'),
  ('ford', 'mustang mach-e'),
  ('ford', 'ranger'),
  ('ford', 'transit'),
  ('genesis', 'g70'),
  ('genesis', 'g80'),
  ('genesis', 'g90'),
  ('genesis', 'gv60'),
  ('genesis', 'gv60 magma'),
  ('genesis', 'gv70'),
  ('genesis', 'gv80'),
  ('gmc', 'acadia'),
  ('gmc', 'canyon'),
  ('gmc', 'hummer ev pickup'),
  ('gmc', 'hummer ev suv'),
  ('gmc', 'savana'),
  ('gmc', 'sierra'),
  ('gmc', 'sierra hd'),
  ('gmc', 'terrain'),
  ('gmc', 'yukon'),
  ('gmc', 'yukon xl'),
  ('honda', 'accord'),
  ('honda', 'civic'),
  ('honda', 'civic si'),
  ('honda', 'civic type r'),
  ('honda', 'cr-v'),
  ('honda', 'hr-v'),
  ('honda', 'odyssey'),
  ('honda', 'passport'),
  ('honda', 'pilot'),
  ('honda', 'prelude'),
  ('honda', 'prologue'),
  ('honda', 'ridgeline'),
  ('hyundai', 'elantra'),
  ('hyundai', 'elantra n'),
  ('hyundai', 'ioniq 5'),
  ('hyundai', 'ioniq 5 n'),
  ('hyundai', 'ioniq 6 n'),
  ('hyundai', 'ioniq 9'),
  ('hyundai', 'kona'),
  ('hyundai', 'nexo'),
  ('hyundai', 'palisade'),
  ('hyundai', 'santa cruz'),
  ('hyundai', 'sonata'),
  ('hyundai', 'tucson'),
  ('hyundai', 'venue'),
  ('infiniti', 'qx60'),
  ('infiniti', 'qx65'),
  ('infiniti', 'qx80'),
  ('jaguar', 'f-pace'),
  ('jeep', 'cherokee'),
  ('jeep', 'compass'),
  ('jeep', 'gladiator'),
  ('jeep', 'grand cherokee'),
  ('jeep', 'grand cherokee l'),
  ('jeep', 'grand wagoneer'),
  ('jeep', 'grand wagoneer l'),
  ('jeep', 'recon'),
  ('jeep', 'wagoneer s'),
  ('jeep', 'wrangler'),
  ('kia', 'carnival'),
  ('kia', 'ev3'),
  ('kia', 'ev6'),
  ('kia', 'ev9'),
  ('kia', 'k4'),
  ('kia', 'k5'),
  ('kia', 'niro'),
  ('kia', 'seltos'),
  ('kia', 'sorento'),
  ('kia', 'sportage'),
  ('kia', 'telluride'),
  ('land rover', 'discovery'),
  ('land rover', 'discovery sport'),
  ('land rover', 'range rover'),
  ('land rover', 'range rover evoque'),
  ('land rover', 'range rover sport'),
  ('land rover', 'range rover velar'),
  ('lexus', 'es'),
  ('lexus', 'is'),
  ('lexus', 'lc'),
  ('lexus', 'ls'),
  ('lexus', 'lx'),
  ('lexus', 'nx'),
  ('lexus', 'rx'),
  ('lexus', 'rz'),
  ('lexus', 'tx'),
  ('lexus', 'ux'),
  ('lincoln', 'aviator'),
  ('lincoln', 'corsair'),
  ('lincoln', 'nautilus'),
  ('lincoln', 'navigator'),
  ('lincoln', 'navigator l'),
  ('lucid', 'air'),
  ('lucid', 'gravity'),
  ('mazda', 'cx-30'),
  ('mazda', 'cx-5'),
  ('mazda', 'cx-50'),
  ('mazda', 'cx-70'),
  ('mazda', 'cx-90'),
  ('mazda', 'mazda3'),
  ('mazda', 'mx-5'),
  ('mercedes-benz', 'cla-class'),
  ('mercedes-benz', 'cle'),
  ('mercedes-benz', 'e-class'),
  ('mercedes-benz', 'eqe-class suv'),
  ('mercedes-benz', 'eqs-class suv'),
  ('mercedes-benz', 'esprinter'),
  ('mercedes-benz', 'g-class'),
  ('mercedes-benz', 'glc-class'),
  ('mercedes-benz', 's-class'),
  ('mercedes-benz', 'sl-class'),
  ('mercedes-benz', 'sprinter'),
  ('mini', 'cooper convertible'),
  ('mini', 'countryman'),
  ('mini', 'hardtop'),
  ('mitsubishi', 'outlander'),
  ('mitsubishi', 'outlander sport'),
  ('nissan', 'altima'),
  ('nissan', 'ariya mpv'),
  ('nissan', 'armada'),
  ('nissan', 'frontier'),
  ('nissan', 'kicks mpv'),
  ('nissan', 'leaf'),
  ('nissan', 'murano'),
  ('nissan', 'nissan z'),
  ('nissan', 'pathfinder'),
  ('nissan', 'rogue'),
  ('nissan', 'sentra'),
  ('polestar', 'polestar 2'),
  ('polestar', 'polestar 3'),
  ('polestar', 'polestar 4'),
  ('porsche', '911'),
  ('porsche', 'cayenne'),
  ('porsche', 'macan'),
  ('porsche', 'panamera'),
  ('porsche', 'taycan'),
  ('ram', '1500'),
  ('ram', '2500'),
  ('ram', '3500'),
  ('ram', 'promaster 1500'),
  ('ram', 'promaster 2500'),
  ('ram', 'promaster 3500'),
  ('rivian', 'r1s'),
  ('rivian', 'r1t'),
  ('rivian', 'r2'),
  ('subaru', 'ascent'),
  ('subaru', 'brz'),
  ('subaru', 'crosstrek'),
  ('subaru', 'forester'),
  ('subaru', 'impreza'),
  ('subaru', 'outback'),
  ('subaru', 'solterra'),
  ('subaru', 'trailseeker'),
  ('subaru', 'uncharted'),
  ('subaru', 'wrx'),
  ('tesla', 'cybercab'),
  ('tesla', 'cybertruck'),
  ('tesla', 'model 3'),
  ('tesla', 'model y'),
  ('toyota', '4runner'),
  ('toyota', 'bz'),
  ('toyota', 'bz woodland'),
  ('toyota', 'c-hr'),
  ('toyota', 'camry'),
  ('toyota', 'corolla'),
  ('toyota', 'corolla cross'),
  ('toyota', 'crown'),
  ('toyota', 'crown signia'),
  ('toyota', 'gr corolla'),
  ('toyota', 'gr86'),
  ('toyota', 'grand highlander'),
  ('toyota', 'highlander'),
  ('toyota', 'land cruiser'),
  ('toyota', 'mirai'),
  ('toyota', 'prius'),
  ('toyota', 'prius prime (phev)'),
  ('toyota', 'rav4'),
  ('toyota', 'rav4 prime (phev)'),
  ('toyota', 'sequoia'),
  ('toyota', 'sienna'),
  ('toyota', 'supra'),
  ('toyota', 'tacoma'),
  ('toyota', 'tundra'),
  ('volkswagen', 'atlas'),
  ('volkswagen', 'golf gti'),
  ('volkswagen', 'golf r'),
  ('volkswagen', 'id.4'),
  ('volkswagen', 'jetta'),
  ('volkswagen', 'jetta gli'),
  ('volkswagen', 'taos'),
  ('volkswagen', 'tiguan'),
  ('volvo', 'ec40'),
  ('volvo', 'ex30'),
  ('volvo', 'ex30 cc'),
  ('volvo', 'ex40'),
  ('volvo', 'ex60'),
  ('volvo', 'ex90'),
  ('volvo', 's90'),
  ('volvo', 'v60cc'),
  ('volvo', 'v90cc'),
  ('volvo', 'xc40'),
  ('volvo', 'xc60'),
  ('volvo', 'xc90')
  );

-- Apply reviewed make/model class clarifications across model years.
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'buick'
  and lower(trim(model)) = 'enclave';
update public.vehicle_lookup
set vehicle_class = 'van', pricing_group = 'Van', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'chrysler'
  and lower(trim(model)) = 'grand voyager';
update public.vehicle_lookup
set vehicle_class = 'van', pricing_group = 'Van', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'chrysler'
  and lower(trim(model)) = 'town and country';
update public.vehicle_lookup
set vehicle_class = 'van', pricing_group = 'Van', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'chrysler'
  and lower(trim(model)) = 'voyager';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'ford'
  and lower(trim(model)) = 'mustang mach-e';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'genesis'
  and lower(trim(model)) = 'gv60';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'genesis'
  and lower(trim(model)) = 'gv70';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'genesis'
  and lower(trim(model)) = 'gv80';
update public.vehicle_lookup
set vehicle_class = 'truck', pricing_group = 'Truck', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'gmc'
  and lower(trim(model)) = 'hummer ev pickup';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'gmc'
  and lower(trim(model)) = 'hummer ev suv';
update public.vehicle_lookup
set vehicle_class = 'coupe', pricing_group = 'Coupe', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'honda'
  and lower(trim(model)) = 'prelude';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'honda'
  and lower(trim(model)) = 'prologue';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'hyundai'
  and lower(trim(model)) = 'ioniq 5';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'hyundai'
  and lower(trim(model)) = 'ioniq 5 n';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'hyundai'
  and lower(trim(model)) = 'ioniq 9';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'hyundai'
  and lower(trim(model)) = 'kona';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'hyundai'
  and lower(trim(model)) = 'nexo';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'hyundai'
  and lower(trim(model)) = 'venue';
update public.vehicle_lookup
set vehicle_class = 'sedan', pricing_group = 'Sedan', classification_source = 'manual_correction_infiniti_q_series', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'infiniti'
  and lower(trim(model)) = 'q45';
update public.vehicle_lookup
set vehicle_class = 'sedan', pricing_group = 'Sedan', classification_source = 'manual_correction_infiniti_q_series', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'infiniti'
  and lower(trim(model)) = 'q50';
update public.vehicle_lookup
set vehicle_class = 'coupe', pricing_group = 'Coupe', classification_source = 'manual_correction_infiniti_q_series', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'infiniti'
  and lower(trim(model)) = 'q60';
update public.vehicle_lookup
set vehicle_class = 'sedan', pricing_group = 'Sedan', classification_source = 'manual_correction_infiniti_q_series', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'infiniti'
  and lower(trim(model)) = 'q70';
update public.vehicle_lookup
set vehicle_class = 'sedan', pricing_group = 'Sedan', classification_source = 'manual_correction_infiniti_q_series', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'infiniti'
  and lower(trim(model)) = 'q70l';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'infiniti'
  and lower(trim(model)) = 'qx80';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'jeep'
  and lower(trim(model)) = 'grand wagoneer';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'jeep'
  and lower(trim(model)) = 'grand wagoneer l';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'jeep'
  and lower(trim(model)) = 'recon';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'jeep'
  and lower(trim(model)) = 'wagoneer s';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'kia'
  and lower(trim(model)) = 'niro';
update public.vehicle_lookup
set vehicle_class = 'sedan', pricing_group = 'Sedan', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'lexus'
  and lower(trim(model)) = 'ls';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'lexus'
  and lower(trim(model)) = 'tx';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'lincoln'
  and lower(trim(model)) = 'navigator l';
update public.vehicle_lookup
set vehicle_class = 'coupe', pricing_group = 'Coupe', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'mazda'
  and lower(trim(model)) = 'mx-5';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'mercedes-benz'
  and lower(trim(model)) = 'eqe-class suv';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'mercedes-benz'
  and lower(trim(model)) = 'eqs-class suv';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'mercedes-benz'
  and lower(trim(model)) = 'g-class';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'mercedes-benz'
  and lower(trim(model)) = 'gla-class';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'mercedes-benz'
  and lower(trim(model)) = 'glb-class';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'mercedes-benz'
  and lower(trim(model)) = 'glc-class';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'mercedes-benz'
  and lower(trim(model)) = 'gle-class';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'mercedes-benz'
  and lower(trim(model)) = 'gls-class';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'mini'
  and lower(trim(model)) = 'countryman';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'mitsubishi'
  and lower(trim(model)) = 'outlander';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'mitsubishi'
  and lower(trim(model)) = 'outlander sport';
update public.vehicle_lookup
set vehicle_class = 'coupe', pricing_group = 'Coupe', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'nissan'
  and lower(trim(model)) = 'nissan z';
update public.vehicle_lookup
set vehicle_class = 'van', pricing_group = 'Van', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'nissan'
  and lower(trim(model)) = 'nv';
update public.vehicle_lookup
set vehicle_class = 'coupe', pricing_group = 'Coupe', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'subaru'
  and lower(trim(model)) = 'brz';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'subaru'
  and lower(trim(model)) = 'solterra';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'subaru'
  and lower(trim(model)) = 'trailseeker';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'subaru'
  and lower(trim(model)) = 'uncharted';
update public.vehicle_lookup
set vehicle_class = 'sedan', pricing_group = 'Sedan', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'subaru'
  and lower(trim(model)) = 'wrx';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'toyota'
  and lower(trim(model)) = 'bz';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'toyota'
  and lower(trim(model)) = 'bz woodland';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'toyota'
  and lower(trim(model)) = 'c-hr';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'toyota'
  and lower(trim(model)) = 'corolla cross';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'toyota'
  and lower(trim(model)) = 'crown signia';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'volkswagen'
  and lower(trim(model)) = 'atlas';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'volkswagen'
  and lower(trim(model)) = 'atlas cross sport';
update public.vehicle_lookup
set vehicle_class = 'sedan', pricing_group = 'Sedan', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'volkswagen'
  and lower(trim(model)) = 'jetta';
update public.vehicle_lookup
set vehicle_class = 'sedan', pricing_group = 'Sedan', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'volkswagen'
  and lower(trim(model)) = 'jetta gli';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'volvo'
  and lower(trim(model)) = 'v60cc';
update public.vehicle_lookup
set vehicle_class = 'suv', pricing_group = 'SUV', classification_source = 'manual_vehicle_class_review_20260905', review_status = 'ok', is_commercial = false
where lower(trim(make)) = 'volvo'
  and lower(trim(model)) = 'v90cc';

commit;
